# Generated by Django 3.2 on 2022-09-06 13:09

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('email',
                 models.EmailField(
                     max_length=254)),
                ('phone_number',
                 models.CharField(
                     max_length=20)),
                ('issue',
                 models.IntegerField(
                     choices=[
                         (1,
                          'Delivery time'),
                         (2,
                          'Customer service'),
                         (3,
                          'Food quality'),
                         (4,
                          'Something else')])),
                ('comment',
                 djrichtextfield.models.RichTextField(
                     max_length=10000)),
                ('user',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='profiles.userprofile')),
            ],
        ),
    ]
