# Generated by Django 3.2 on 2022-05-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order',
            new_name='invoice',
        ),
    ]
