# Generated by Django 3.2 on 2022-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220524_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_order',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
