# Generated by Django 3.2 on 2022-09-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dietrequirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietrequirements',
            old_name='dietRequirement',
            new_name='assignedProduct',
        ),
    ]
